### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by LeonardoGentile** [ansel-app/ansel#7]
Hello,
any plan to support other Os Platforms? 
I'm particularly interested in MacOs support. 
What would be necessary to make this work under MacOs? Several  linux packages could be installed using brew

**Comment by m0g** [comment]
Hey,
there is already a partial support for OSX that you can find here: https://github.com/m0g/ansel/tree/osx
However, I do not have access to a mac, so it is hard to provide support for this platform.

**Comment by LeonardoGentile** [comment]
@m0g thanks 👍 
I'm wondering what would be the differences, only the underlying image-manipulation libraries?

Can't images be manipulated only using cross-platform npm packages?

I do have access to mac machine, let me know how can I test/help you

**Comment by LeonardoGentile** [comment]
Hello,
I've re-installed and tested on OSX after @til-schneider PR.

I am able to launch the main window and from there chose the main directory.
After that it doesn't see anything in that directory even tough it correctly contains several images. 
Ctrl-R or clicking the refresh button doesn't help.

I suspect it's a PATH thing, probably some spaces along the path chosen, I will take a look even tough I'm a newbie on Electron.

Apart that, at the moment it seems impossible to reset or change the main directory (at least on OSX). I even deleted the folder `~/Library/Application\ Support/Ansel` but the first page where it asks where the main folder is located doesn't pop up anymore and I couldn't find another way from the ui or menu where I can set this.

Is it a missing feature or a OSX bug somehow?

The electron debugger or the terminal console don't print any error.

**Comment by til-schneider** [comment]
I used a path without spaces for testing. So yes, this may cause problems.

I'm not sure how you are creating and running Ansel. But if you build it from source, the settings are located in the project directory under `dot-ansel`. When you delete `settings.json`, you should be asked for the directories on the next startup.

**Comment by LeonardoGentile** [comment]
I confirm, after deleting the `settings.json` and re-setting the main directory to somewhere else (with no space) I get the same problem, the app doesn't see. By clicking the scan button or cmd-r it stays in "Scanning 0%" forever

**Comment by til-schneider** [comment]
Please open the developer console (via menu or `Cmd`+`Alt`+`I`) and check if there are any errors in the console.

**Comment by LeonardoGentile** [comment]
As said above, there isn't any. There are only redux logged action   
  
![ansel_-_dev_mode](https://user-images.githubusercontent.com/412061/39633965-c69f0416-4fb9-11e8-9b4e-5bafc53a4c25.png)

**Comment by til-schneider** [comment]
Hmm, strange...

- Which version are you using? https://github.com/m0g/ansel/ or https://github.com/til-schneider/ansel/ ? And which branch?
- Do you have errors in the Terminal (where you entered `npm start`)?
- Can you try to only import the directory `specs/photos` containing the test photos?

**Comment by LeonardoGentile** [comment]
Sorry I did forget to set the versions directory 🙄 
I tough it was not necessary as I skimmed the last PR discussion and there was an idea to store processed image information in Picasa format. I think that is for the future 😄 

By the way, I'm using m0g/ansel on branch master, I assume the dev will continue here as the discussion on collaboration went further, isn't it?

**Comment by til-schneider** [comment]
I don't know how versions work. I'm just using an empty directory for versions.

I will develop in til-schneider/ansel and open pull requests in m0g/ansel when a feature is mature.

**Comment by m0g** [comment]
The work flow I envisioned for Ansel was the following:

* Download RAW pictures from the DSLR's sd-card to the `photos/` folder.
* Import them inside Ansel via folder scan (`ctrl+r`).
* Organize pictures (delete, flag, tag...)
* Right click on a picture to export it to a third party software (gimp, rawtherapee, photoshop) for post processing.
* Ansel create a copy of the file (either raw, jpg or tiff) and opens it with the third party software.
* On the third party application, once the post processing is done, export the file into the `versions/` directory (without changing the name).
* Ansel will directly detect which file it is, and create a new version in the database, keeping both the original and the new version (hence the diff view).

Hope I'm clear in my explanations.

**Comment by til-schneider** [comment]
This is fixed with [version 1.0.0](https://github.com/ansel-app/ansel/releases/tag/v1.0.0)
